### ISSUE TITLE
Peer to peer Code Review: 8 March

### ISSUE THREAD

**Issue by shahedakhatoon** [aboongm/Portfolio-setup-and-mobile-version-skeleton#12]
## Add the following:
1. Scroll smooth in the CSS file

**Comment by razvanso** [comment]
Your code is working and you've been quite fast developing it - great! You could improve it by:
- making the background of the menu semi-transparent and use a blur effect to come closer to the design
- naming things is an important part of developing maintainable code, so that class names, variables and even branch names could tell you more in the future than only you know right now.

Keep up the good work!

**Comment by aboongm** [comment]
The naming of file and css class was pertinent. I have change the name of mobile.css to dynamic.css.
